GET http://localhost:4201/v1

####

POST http://localhost:4201/v1/register
Content-Type: application/json

{
    "name": "ebebe",
    "surname": "many",
    "username": "test3",
    "email": "uwa5@mail.com",
    "password": "potezne"
}

####
POST http://localhost:4201/v1/login
Content-Type: application/json

{
    "email": "uwa5@mail.com",
    "password": "potezne"
}


####
POST http://localhost:4201/v1/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjYzMTEzMzEsImlkZW50aXR5a2V5IjoiNjBlZGZkM2RmNTRiYzcxNzVmOGU5MDM4In0.DE4lKirl0a_GId77nQ5jni_Te0MqBYmVlYEwDNDmroY

####
GET http://localhost:4201/v1/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjYyMTc2NzEsImlkZW50aXR5a2V5IjoiNjBlZGZkM2RmNTRiYzcxNzVmOGU5MDM4Iiwic3ViIjoxfQ.hbm7ejZdb8xX5nQLG8XyF49vQEYUAl88Sd6zggo6w1g
Content-Type: "application/json"

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjYyMTc4NzAsImlkZW50aXR5a2V5IjoiNjBlZGZkM2RmNTRiYzcxNzVmOGU5MDM4Iiwic3ViIjoxfQ.pFMbv7-kbdy-fKWnCwyByJOqGpDDZSYA5jz5-6MqF-w"
}

####
GET http://localhost:4201/v1/user/60e35a7853f9b65906dcad42
