GET http://localhost:4201/v1

####

POST http://localhost:4201/v1/register
Content-Type: application/json

{
    "username": "test",
    "email": "uwa3mail.com",
    "password": "potezne"
}

####
POST http://localhost:4201/v1/login
Content-Type: application/json

{
    "email": "uwa4@mail.com",
    "password": "potezne"
}


####
POST http://localhost:4201/v1/logout
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjU0OTc2MTMsImlkZW50aXR5S2V5IjoidGVzdCIsIm9yaWdfaWF0IjoxNjI1NDk3NDkzfQ.XRD9CRrH2GHWBHZ7H_Olym3c6GXC9CxY4kMLTmo7QKU; Path=/; Max-Age=120


####
GET http://localhost:4201/v1/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjU0OTc2MzgsImlkZW50aXR5S2V5IjoidGVzdCIsIm9yaWdfaWF0IjoxNjI1NDk3NTE4fQ.Z842T8Gn4aApgReH7xRzOnnrZ89cokZdIy8uAJggyuw
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjU0OTc2MzgsImlkZW50aXR5S2V5IjoidGVzdCIsIm9yaWdfaWF0IjoxNjI1NDk3NTE4fQ.Z842T8Gn4aApgReH7xRzOnnrZ89cokZdIy8uAJggyuw; Path=/; Max-Age=120