GET http://localhost:4201/v1

####

POST http://localhost:4201/v1/register
Content-Type: application/json

{
    "name": "John",
    "surname": "Doe",
    "username": "john_oe",
    "email": "joemmma@mail.com",
    "password": "verystrongpasswd"
}

####
POST http://localhost:4201/v1/login
Content-Type: application/json

{
    "email": "joemmma@mail.com",
    "password": "verystrongpasswd"
}


####
POST http://localhost:4201/v1/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjYzMTEzMzEsImlkZW50aXR5a2V5IjoiNjBlZGZkM2RmNTRiYzcxNzVmOGU5MDM4In0.DE4lKirl0a_GId77nQ5jni_Te0MqBYmVlYEwDNDmroY

####
POST http://localhost:4201/v1/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzAxODQ0OTIsImlkZW50aXR5a2V5IjoiNjEyYTE3NzMyNTJhYmMyMjZkZjk2NDY1In0.WasPjMIbatCBKebF5z_bOzlK1LOmhLRM8A_jWeY5wDA

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzAxODQ0OTIsImlkZW50aXR5a2V5IjoiNjEyYTE3NzMyNTJhYmMyMjZkZjk2NDY1In0.WasPjMIbatCBKebF5z_bOzlK1LOmhLRM8A_jWeY5wDA"
}

####
GET http://localhost:4201/v1/user/612a1773252abc226df96465
