// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"go.mongodb.org/mongo-driver/mongo"
	"golang/handler"
	"golang/middleware"
	"golang/redirect"
	"golang/user"
)

// Injectors from wire.go:

func InitializeHandler(client *mongo.Client) handler.Handler {
	userRepository := user.NewUserRepository(client)
	userService := user.NewUserService(userRepository)
	redirectRepository := redirect.NewRedirectRepository(client)
	redirectService := redirect.NewRedirectService(redirectRepository)
	handlerHandler := handler.NewHandler(userService, redirectService)
	return handlerHandler
}

func InitializeAuthMiddleware() middleware.AuthMiddleware {
	authMiddleware := middleware.NewAuthMiddleware()
	return authMiddleware
}
