
CREATE DATABASE JIGDRA;

CREATE TABLE IF NOT EXISTS WORKSPACEUSERS(
	ID			UUID PRIMARY KEY,
	USER_ID		TEXT,
	NICKNAME	VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS WORKSPACES(
	ID					UUID PRIMARY KEY,
	WORKSPACE_USER_ID	UUID
);

CREATE TABLE IF NOT EXISTS TASKS(
	ID					UUID	PRIMARY KEY,
	WORKSPACE_ID		UUID,
	WORKSPACE_USER_ID	UUID
);
