// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/jackc/pgx/v4/pgxpool"
	"go-psql/middleware"
	"go-psql/workspace"
)

// Injectors from wire.go:

func InitializeAuthMiddleware(postgresDatabase *pgxpool.Pool) middleware.AuthMiddleware {
	workspaceUserRepository := workspace.NewWorkspaceUserRepository(postgresDatabase)
	workspaceUserService := workspace.NewWorkspaceUserService(workspaceUserRepository)
	authMiddleware := middleware.NewAuthMiddleware(workspaceUserService)
	return authMiddleware
}

func InitializeWorkspaceFacadeHandler(postgresDatabase *pgxpool.Pool) workspace.WorkspaceFacadeHandler {
	workspaceRepository := workspace.NewWorkspaceRepository(postgresDatabase)
	workspaceService := workspace.NewWorkspaceService(workspaceRepository)
	workspaceUserRepository := workspace.NewWorkspaceUserRepository(postgresDatabase)
	workspaceUserService := workspace.NewWorkspaceUserService(workspaceUserRepository)
	workspaceFacade := workspace.NewWorkspaceFacade(workspaceService, workspaceUserService)
	workspaceFacadeHandler := workspace.NewWorkspaceFacadeHandler(workspaceFacade, workspaceUserService)
	return workspaceFacadeHandler
}
